export default {
    logo: require('../assets/images/Logo.png'),
    backlogo: require('../assets/images/ic_back_arrow.png'),
    homelogo: require('../assets/images/ic_home.png'),
    searchlogo: require("../assets/images/ic_srch.png"),
    addgallerylogo: require("../assets/images/ic_add.png"),
    nodificationlogo: require("../assets/images/ic_notify.png"),
    profilelogo: require("../assets/images/ic_user.png"),
    person: require('../assets/images/ic_1.png'),
    apple: require("../assets/images/ic_apple.png"),
    facebook: require("../assets/images/ic_facebook.png"),
    google: require("../assets/images/ic_google.png"),
    tick: require("../assets/images/ic_blue_tick.png"),
    location: require("../assets/images/ic_loc.png"),
    threedots:require("../assets/images/ic_dots.png"),
    Sharearrow:require("../assets/images/ic_direction.png"),
    user:require("../assets/images/ic_usrr_1.png"),
    key:require("../assets/images/ic_key.png"),
    logout:require("../assets/images/ic_logout.png"),
    edit:require("../assets/images/ic_edit.png"),
    cross:require("../assets/images/ic_cross.png"),
    pluse:require("../assets/images/ic_plus.png"),
    dummyprofile: { uri: "https://images.ctfassets.net/h6goo9gw1hh6/2sNZtFAWOdP1lmQ33VwRN3/24e953b920a9cd0ff2e1d587742a2472/1-intro-photo-final.jpg?w=1200&h=992&fl=progressive&q=70&fm=jpg" },
    dummydata: { uri: "https://w0.peakpx.com/wallpaper/266/1012/HD-wallpaper-street-night-city-neon-road-cars.jpg" },
    dummydata2: { uri: "https://i.pinimg.com/736x/b5/4c/33/b54c33ec87db8a62ec288a74a85926de.jpg" }
}